# ✅ Final surge.conf
#############################################
# Surge Configuration
# Author: SantaG3225
# Repository: https://github.com/SantaG3225/surge-config
# Updated: 2026-05
#############################################
[General]
loglevel = warning

dns-server = 223.5.5.5, 119.29.29.29, 1.1.1.1

hijack-dns = 8.8.8.8:53,8.8.4.4:53,1.1.1.1:53,1.0.0.1:53

always-real-ip = dns.msftncsi.com, *.msftconnecttest.com, *.srv.nintendo.net, *.stun.playstation.net, stun.*, *.fbcdn.net

geoip-maxmind-url = https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb

skip-proxy = 127.0.0.0/8, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 162.14.0.0/16, fc00::/7, fe80::/10, localhost, *.local, *.ts.net, captive.apple.com, passenger.t3go.cn, *.ccb.com, wxh.wo.cn, *.abcchina.com, *.abcchina.com.cn
exclude-simple-hostnames = true
read-etc-hosts = true

internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://cp.cloudflare.com/generate_204
proxy-test-udp = cp.cloudflare.com@1.1.1.1
test-timeout = 3

http-listen = 0.0.0.0:8888
socks5-listen = 0.0.0.0:8889
wifi-access-http-port = 8888
wifi-access-socks5-port = 8889
allow-wifi-access = true
proxy-restricted-to-lan = true

external-controller-access = kkchan@0.0.0.0:6170
http-api = kkchan1981@0.0.0.0:6171
http-api-web-dashboard = true

show-error-page-for-reject = false
block-quic = all-proxy
udp-policy-not-supported-behaviour = DIRECT
udp-priority = false
wifi-assist = false
ipv6 = false // 如无特殊需求不应开启 IPv6，目前网络环境下 IPv6 只会带来问题。
ipv6-vif = disabled
http-api-tls = false
all-hybrid = true
encrypted-dns-server = quic://223.5.5.5, quic://223.6.6.6, https://1.12.12.12/dns-query, https://120.53.53.53/dns-query

#############################################
# Proxy
#############################################

[Proxy]

direct = Direct

☁️ wg-atlantic = wireguard, section-name=atlantic-vpn

Proxy = http, 127.0.0.1, 7890
#############################################
# Rules
#############################################

[Rule]
# Reject rules
RULE-SET,https://jkoch.app/rules/reject.list,REJECT

# Chinq rules
RULE-SET,https://jkoch.app/rules/cn.list,DIRECT

# Direct rules
RULE-SET,https://jkoch.app/rules/direct.list,DIRECT
RULE-SET,https://jkoch.app/rules/apple.list,DIRECT

# Proxy rules
RULE-SET,https://jkoch.app/rules/openai.list,Proxy
RULE-SET,https://jkoch.app/rules/telegram.list,Proxy
RULE-SET,https://jkoch.app/rules/google.list,Proxy
RULE-SET,https://jkoch.app/rules/microsoft.list,Proxy
RULE-SET,https://jkoch.app/rules/proxy.list,Proxy

OR,((RULE-SET,SYSTEM), (RULE-SET,LAN), (GEOIP,CN,no-resolve)),DIRECT

# Final fallback
FINAL,Proxy

#############################################
# Modules
#############################################

[Module]
https://raw.githubusercontent.com/SantaG3225/surge-config/main/modules/adblock.sgmodule





[WireGuard atlantic-vpn]
private-key = 0AMBIvpHUIOwaumdNYQRLdJR7czdqUqkmuFtLB0KEm4=
self-ip = 10.7.0.2
dns-server = 1.1.1.1, 1.0.0.1
mtu = 1280
peer = (public-key = 8VninJkKZXsMh9t3IhWocfGFVFb7ZH7NuB8bHhPxmno=, allowed-ips = "0.0.0.0/0, ::0/0", endpoint = us.jkoch14.app:51820, preshared-key = FdPKb8rsvH9wNCeUL77qBLrTvayHYdTM83KnAXoccCU=, keepalive = 30)
